<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Algorithmic Trading

**Chapter 03 &mdash; Working with Financial Data**

&copy; Dr Yves J Hilpisch | The Python Quants GmbH

http://tpq.io | [training@tpq.io](mailto:training@tpq.io) | [dyjh](http://twitter.com/dyjh)

<img src="https://hilpisch.com/pyalgo_cover_color.png" width="40%">

## Sample Data Set from Eikon

Create the local `data` folder if necessary via

    !mkdir data

You can register for a **free trial account for Eikon** under:

    https://refini.tv/3bvPev5

In [ ]:
!git clone https://github.com/tpq-classes/python_for_algo_trading_core.git
import sys
sys.path.append('python_for_algo_trading_core')

In [1]:
import eikon as ek
import warnings; warnings.simplefilter('ignore')

In [2]:
path = '../../../'  # adjust the path to your own one

In [3]:
import configparser
config = configparser.ConfigParser()
config.read(path + 'pyalgo.cfg')

['../../../pyalgo.cfg']

ek.set_app_key(config['eikon']['app_key'])

data = ek.get_timeseries('AAPL.O',
                         start_date='2020-04-01',
                         end_date='2020-04-30',
                         interval='daily',
                         fields=['*'])

data.tail()

data.to_csv('AAPL.csv')

## Reading Financial Data From Different Sources

### The Data Set

In [4]:
fn = 'AAPL.csv'

In [5]:
with open(fn, 'r') as f:
    for _ in range(5):
        print(f.readline(), end='')

Date,HIGH,CLOSE,LOW,OPEN,COUNT,VOLUME
2020-04-01,248.72,240.91,239.13,246.5,460606.0,44054638.0
2020-04-02,245.15,244.93,236.9,240.34,380294.0,41483493.0
2020-04-03,245.7,241.41,238.9741,242.8,293699.0,32470017.0
2020-04-06,263.11,262.47,249.38,250.9,486681.0,50455071.0

### Reading from a CSV File with Python

In [6]:
import csv

In [7]:
csv_reader = csv.reader(open(fn, 'r'))

In [8]:
data = [l for l in csv_reader]

In [9]:
data[:5]

[['Date', 'HIGH', 'CLOSE', 'LOW', 'OPEN', 'COUNT', 'VOLUME'],
 ['2020-04-01',
  '248.72',
  '240.91',
  '239.13',
  '246.5',
  '460606.0',
  '44054638.0'],
 ['2020-04-02',
  '245.15',
  '244.93',
  '236.9',
  '240.34',
  '380294.0',
  '41483493.0'],
 ['2020-04-03',
  '245.7',
  '241.41',
  '238.9741',
  '242.8',
  '293699.0',
  '32470017.0'],
 ['2020-04-06',
  '263.11',
  '262.47',
  '249.38',
  '250.9',
  '486681.0',
  '50455071.0']]

In [10]:
csv_reader = csv.DictReader(open(fn, 'r'))

In [11]:
data = [l for l in csv_reader]

In [12]:
data[:3]

[{'Date': '2020-04-01',
  'HIGH': '248.72',
  'CLOSE': '240.91',
  'LOW': '239.13',
  'OPEN': '246.5',
  'COUNT': '460606.0',
  'VOLUME': '44054638.0'},
 {'Date': '2020-04-02',
  'HIGH': '245.15',
  'CLOSE': '244.93',
  'LOW': '236.9',
  'OPEN': '240.34',
  'COUNT': '380294.0',
  'VOLUME': '41483493.0'},
 {'Date': '2020-04-03',
  'HIGH': '245.7',
  'CLOSE': '241.41',
  'LOW': '238.9741',
  'OPEN': '242.8',
  'COUNT': '293699.0',
  'VOLUME': '32470017.0'}]

In [13]:
sum([float(l['CLOSE']) for l in data]) / len(data)

272.38619047619045

### Reading from a CSV File with numpy

In [14]:
import datetime
import numpy as np

In [15]:
# help(np.genfromtxt)

In [16]:
t = b'2020-04-06'

In [17]:
datetime.datetime.strptime(t.decode(), '%Y-%m-%d')

datetime.datetime(2020, 4, 6, 0, 0)

In [18]:
con = {0: lambda t: datetime.datetime.strptime(t, '%Y-%m-%d')}

In [19]:
sa = np.genfromtxt(fn, delimiter=',', dtype=None, names=True, converters=con)

In [20]:
sa

array([(datetime.datetime(2020, 4, 1, 0, 0), 248.72  , 240.91, 239.13  , 246.5 , 460606., 44054638.),
       (datetime.datetime(2020, 4, 2, 0, 0), 245.15  , 244.93, 236.9   , 240.34, 380294., 41483493.),
       (datetime.datetime(2020, 4, 3, 0, 0), 245.7   , 241.41, 238.9741, 242.8 , 293699., 32470017.),
       (datetime.datetime(2020, 4, 6, 0, 0), 263.11  , 262.47, 249.38  , 250.9 , 486681., 50455071.),
       (datetime.datetime(2020, 4, 7, 0, 0), 271.7   , 259.43, 259.    , 270.8 , 467375., 50721831.),
       (datetime.datetime(2020, 4, 8, 0, 0), 267.37  , 266.07, 261.23  , 262.74, 391246., 42223821.),
       (datetime.datetime(2020, 4, 9, 0, 0), 270.07  , 267.99, 264.7   , 268.7 , 415870., 40529123.),
       (datetime.datetime(2020, 4, 13, 0, 0), 273.7   , 273.25, 265.83  , 268.31, 343829., 32755731.),
       (datetime.datetime(2020, 4, 14, 0, 0), 288.25  , 287.05, 278.05  , 280.  , 476983., 48748672.),
       (datetime.datetime(2020, 4, 15, 0, 0), 286.33  , 284.43, 280.63  , 282.4 , 312185., 32788641.),
       (datetime.datetime(2020, 4, 16, 0, 0), 288.1975, 286.69, 282.3502, 287.38, 377056., 39281290.),
       (datetime.datetime(2020, 4, 17, 0, 0), 286.945 , 282.8 , 276.86  , 284.69, 571192., 53812478.),
       (datetime.datetime(2020, 4, 20, 0, 0), 281.68  , 276.93, 276.85  , 277.95, 357160., 32503750.),
       (datetime.datetime(2020, 4, 21, 0, 0), 277.25  , 268.37, 265.43  , 276.28, 530768., 45247893.),
       (datetime.datetime(2020, 4, 22, 0, 0), 277.9   , 276.1 , 272.2   , 273.61, 287132., 29264342.),
       (datetime.datetime(2020, 4, 23, 0, 0), 281.75  , 275.03, 274.87  , 275.87, 318314., 31203582.),
       (datetime.datetime(2020, 4, 24, 0, 0), 283.01  , 282.97, 277.    , 277.2 , 306176., 31627183.),
       (datetime.datetime(2020, 4, 27, 0, 0), 284.54  , 283.17, 279.95  , 281.8 , 300771., 29271893.),
       (datetime.datetime(2020, 4, 28, 0, 0), 285.83  , 278.58, 278.2   , 285.08, 285384., 28001187.),
       (datetime.datetime(2020, 4, 29, 0, 0), 289.67  , 287.73, 283.89  , 284.73, 324890., 34320204.),
       (datetime.datetime(2020, 4, 30, 0, 0), 294.53  , 293.8 , 288.35  , 289.96, 471129., 45765968.)],
      dtype=[('Date', 'O'), ('HIGH', '<f8'), ('CLOSE', '<f8'), ('LOW', '<f8'), ('OPEN', '<f8'), ('COUNT', '<f8'), ('VOLUME', '<f8')])

In [21]:
sa['CLOSE'].mean()

np.float64(272.38619047619056)

### Reading from a CSV File with pandas

In [22]:
import pandas as pd
pd.__version__
import openpyxl
openpyxl.__version__

'3.1.5'

In [23]:
data = pd.read_csv(fn, index_col=0,
                   parse_dates=True)

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21 entries, 2020-04-01 to 2020-04-30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HIGH    21 non-null     float64
 1   CLOSE   21 non-null     float64
 2   LOW     21 non-null     float64
 3   OPEN    21 non-null     float64
 4   COUNT   21 non-null     float64
 5   VOLUME  21 non-null     float64
dtypes: float64(6)
memory usage: 1.1 KB

In [25]:
data.tail()

              HIGH   CLOSE     LOW    OPEN     COUNT      VOLUME
Date
2020-04-24  283.01  282.97  277.00  277.20  306176.0  31627183.0
2020-04-27  284.54  283.17  279.95  281.80  300771.0  29271893.0
2020-04-28  285.83  278.58  278.20  285.08  285384.0  28001187.0
2020-04-29  289.67  287.73  283.89  284.73  324890.0  34320204.0
2020-04-30  294.53  293.80  288.35  289.96  471129.0  45765968.0

In [26]:
data['CLOSE'].mean()

np.float64(272.38619047619056)

### Exporting to Excel and JSON

In [27]:
#data.to_excel(path + 'aapl.xls', 'AAPL')

In [28]:
data.to_excel(path + 'aapl.xlsx', 'AAPL')

In [29]:
data.to_json(path + 'aapl.json')

In [30]:
ls -n $path/aapl.*

-rw-r--r-- 1 65534 65534 3067 Jul 24 09:48 ../../..//aapl.json
-rw-r--r-- 1 65534 65534 6098 Jul 24 09:48 ../../..//aapl.xlsx

### Reading from Excel and JSON

In [31]:
data_copy_1 = pd.read_excel(path + 'aapl.xlsx', 'AAPL', index_col=0)

In [32]:
data_copy_1.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
Date
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071
2020-04-07  271.70  259.43  259.0000  270.80  467375  50721831

In [33]:
data_copy_1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21 entries, 2020-04-01 to 2020-04-30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HIGH    21 non-null     float64
 1   CLOSE   21 non-null     float64
 2   LOW     21 non-null     float64
 3   OPEN    21 non-null     float64
 4   COUNT   21 non-null     int64
 5   VOLUME  21 non-null     int64
dtypes: float64(4), int64(2)
memory usage: 1.1 KB

In [34]:
data_copy_2 = pd.read_json(path + 'aapl.json')

In [35]:
data_copy_2.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071
2020-04-07  271.70  259.43  259.0000  270.80  467375  50721831

In [36]:
data_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21 entries, 2020-04-01 to 2020-04-30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HIGH    21 non-null     float64
 1   CLOSE   21 non-null     float64
 2   LOW     21 non-null     float64
 3   OPEN    21 non-null     float64
 4   COUNT   21 non-null     int64
 5   VOLUME  21 non-null     int64
dtypes: float64(4), int64(2)
memory usage: 1.1 KB

In [37]:
!rm $path/aapl.*

## Working with Open Data Sources

In [38]:
import quandl as q

In [41]:
help(q.get)

Help on function get in module quandl.get:

get(dataset, **kwargs)
    Return dataframe of requested dataset from Quandl.
    :param dataset: str or list, depending on single dataset usage or multiset usage
            Dataset codes are available on the Quandl website
    :param str api_key: Downloads are limited to 50 unless api_key is specified
    :param str start_date, end_date: Optional datefilers, otherwise entire
           dataset is returned
    :param str collapse: Options are daily, weekly, monthly, quarterly, annual
    :param str transform: options are diff, rdiff, cumul, and normalize
    :param int rows: Number of rows which will be returned
    :param str order: options are asc, desc. Default: `asc`
    :param str returns: specify what format you wish your dataset returned as,
        either `numpy` for a numpy ndarray or `pandas`. Default: `pandas`
    :returns: :class:`pandas.DataFrame` or :class:`numpy.ndarray`
    Note that Pandas expects timeseries data to be sorted ascending for most
    timeseries functionality to work.
    Any other `kwargs` passed to `get` are sent as field/value params to Quandl
    with no interference.

In [39]:
data = q.get('BCHAIN/MKPRU', api_key=config['quandl']['api_key'])

QuandlError: (Status 403) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@quandl.com.

In [ ]:
data.info()

In [ ]:
data['Value'].resample('A').last()

In [ ]:
data = q.get('FSE/SAP_X', start_date='2018-1-1',
             end_date='2020-05-01',
             api_key=config['quandl']['api_key'])

In [ ]:
data.info()

In [ ]:
q.ApiConfig.api_key = config['quandl']['api_key']

In [ ]:
vol = q.get('VOL/MSFT')

In [ ]:
vol.iloc[:, :10].info()

In [ ]:
vol[['IvMean30', 'IvMean60', 'IvMean90']].tail()

## Refinitiv Eikon Data API

`pip install eikon` &mdash; Requires a paid subscription.

import eikon as ek

ek.set_app_key(config['eikon']['app_key'])

### Retrieving Historical Structured Data

import warnings; warnings.simplefilter('ignore')

symbols = ['AAPL.O', 'MSFT.O', 'GOOG.O']

data = ek.get_timeseries(symbols,
                         start_date='2020-01-01',
                         end_date='2020-05-01',
                         interval='daily',
                         fields=['*'])

In [ ]:
# data

data.keys()

type(data['AAPL.O'])

data['AAPL.O'].info()

data['AAPL.O'].tail()

%%time
data = ek.get_timeseries(symbols,
                         start_date='2020-05-05',
                         end_date='2020-05-06',
                         interval='minute',
                         fields='*')

print(data['GOOG.O'].loc['2020-05-05 16:00:00':
                         '2020-05-05 16:04:00'].round(1))

for sym in symbols:
    print('\n' + sym + '\n', data[sym].iloc[-300:-295].round(1))

%%time
data = ek.get_timeseries(symbols[0],
                         start_date='2020-05-05 15:00:00',
                         end_date='2020-05-05 15:15:00',
                         interval='tick',
                         fields=['*'])

data.info()

data.head()

resampled = data.resample('30s', label='right').agg(
            {'VALUE': 'last', 'VOLUME': 'sum'})

resampled.tail()

### Retrieving Historical Unstructured Data

headlines = ek.get_news_headlines(query='R:AAPL.O macbook',
                                  count=5,
                                  date_from='2020-4-1',
                                  date_to='2020-5-1')

headlines

story = headlines.iloc[0]

story

news_text = ek.get_news_story(story['storyId'])

from IPython.display import HTML

HTML(news_text)

## Storing Financial Data Efficiently

### Storing DataFrame Objects

In [ ]:
from pylab import plt
plt.style.use('seaborn-v0_8')

In [ ]:
from sample_data import generate_sample_data

In [ ]:
print(generate_sample_data(rows=5, cols=4))

In [ ]:
%time data = generate_sample_data(rows=150, cols=10).round(4)

In [ ]:
data.plot(figsize=(10, 6), legend=False);

In [ ]:
%time data = generate_sample_data(rows=5e6, cols=10).round(4)

In [ ]:
data.info()

In [ ]:
h5 = pd.HDFStore(path + 'data.h5', 'w')

In [ ]:
%time h5['data'] = data

In [ ]:
h5

In [ ]:
ls -n data/data.*

In [ ]:
h5.close()

In [ ]:
h5 = pd.HDFStore(path + 'data.h5', 'r')

In [ ]:
%time data_copy = h5['data']

In [ ]:
data_copy.info()

In [ ]:
h5.close()

In [ ]:
rm data/data.h5

In [ ]:
%time data.to_hdf(path + 'data.h5', 'data', format='table')

In [ ]:
ls -n $path/data.*

In [ ]:
%time data_copy = pd.read_hdf(path + 'data.h5', 'data')

In [ ]:
data_copy.info()

In [ ]:
import tables as tb

In [ ]:
h5 = tb.open_file(path + 'data.h5', 'r')

In [ ]:
h5

In [ ]:
h5.root.data.table[:3]

In [ ]:
h5.close()

In [ ]:
!rm $path/data.h5

### Using TsTables

In [ ]:
%%time
data = generate_sample_data(rows=2.5e6, cols=5,
                            freq='1s').round(4)

In [ ]:
data.info()

You should install the `tstables` package via:

    pip install git+https://github.com/yhilpisch/tstables

In [ ]:
import tstables

In [ ]:
import tables as tb

In [ ]:
class desc(tb.IsDescription):
    ''' Description of TsTables table structure.
    '''
    timestamp = tb.Int64Col(pos=0)
    No0 = tb.Float64Col(pos=1)
    No1 = tb.Float64Col(pos=2)
    No2 = tb.Float64Col(pos=3)
    No3 = tb.Float64Col(pos=4)
    No4 = tb.Float64Col(pos=5)

In [ ]:
h5 = tb.open_file(path + 'data.h5ts', 'w')

In [ ]:
ts = h5.create_ts('/', 'data', desc)

In [ ]:
h5

In [ ]:
%time ts.append(data)

In [ ]:
# h5

In [ ]:
import datetime

In [ ]:
start = datetime.datetime(2021, 1, 2)

In [ ]:
end = datetime.datetime(2021, 1, 3)

In [ ]:
%time subset = ts.read_range(start, end)

In [ ]:
subset.info()

In [ ]:
start = datetime.datetime(2021, 1, 2, 12, 30, 0)

In [ ]:
end = datetime.datetime(2021, 1, 5, 17, 15, 30)

In [ ]:
%time subset = ts.read_range(start, end)

In [ ]:
subset.info()

In [ ]:
h5.close()

In [ ]:
rm data/*

### Storing Data with SQLite3

In [ ]:
%time data = generate_sample_data(1e6, 5, '1min').round(4)

In [ ]:
data.info()

In [ ]:
import sqlite3 as sq3

In [ ]:
con = sq3.connect(path + 'data.sql')

In [ ]:
%time data.to_sql('data', con)

In [ ]:
ls -n data/data.*

In [ ]:
query = 'SELECT * FROM data WHERE No1 > 105 and No2 < 108'

In [ ]:
%time res = con.execute(query).fetchall()

In [ ]:
res[:5]

In [ ]:
len(res)

In [ ]:
con.close()

In [ ]:
rm $path/data.*

## Oanda Data

In [ ]:
import tpqoa

In [ ]:
api = tpqoa.tpqoa(path + 'pyalgo.cfg')

In [ ]:
oanda = api.get_history('SPX500_USD', '2020-05-05', '2020-05-06', 'M1', 'M')

In [ ]:
oanda.info()

eikon = ek.get_timeseries('SPY',
                         start_date='2020-05-05',
                         end_date='2020-05-06',
                         interval='minute',
                         fields=['*'])

eikon = eikon.loc['2020-05-05 08:00':'2020-05-05 20:00']

eikon.info()

data = pd.DataFrame(eikon['CLOSE'])
data['c'] = oanda['c'].shift(1)
data.columns = ('eikon', 'oanda')

In [ ]:
# data.dropna(inplace=True)

In [ ]:
# data = data.ffill()

data.head()

(data / data.iloc[0]).iloc[:50].plot(figsize=(10, 6));

(data / data.iloc[0]).iloc[-50:].plot(figsize=(10, 6));

data['diff'] = (data / data.iloc[0])['eikon'] - (data / data.iloc[0])['oanda']
data['diff'].mean()

data['diff'].hist(bins=50, figsize=(10, 6));

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>